import React, {Component} from 'react';
import PropTypes from "prop-types";
import {StyleSheet, Text, View, TextInput, FlatList, Picker, ScrollView, TouchableHighlight} from 'react-native';
import {Image as ReactImage} from 'react-native';
import Svg, {Defs, Pattern} from 'react-native-svg';
import {Path as SvgPath} from 'react-native-svg';
import {Text as SvgText} from 'react-native-svg';
import {Image as SvgImage} from 'react-native-svg';

export default class Meusservicos extends Component {

  constructor(props) {
      super(props);
      this.state = {
          
      };
  }


  handlePress(target, owner) {
    if (this.props.onPress) {
        let name;
        let id;
        let index = -1;
        if (target.search("::") > -1) {
            const varCount = target.split("::").length;
            if (varCount === 2) {
                name = target.split("::")[0];
                id = target.split("::")[1];
            } else if (varCount === 3) {
                name = target.split("::")[0];
                index = parseInt(target.split("::")[1]);
                id = target.split("::")[2];
            }
        } else {
            name = target;
        }
        this.props.onPress({ type: 'button', name: name, index: index, id: id, owner: owner });
    }
  }

  handleChangeTextinput(name, value) {
      let id;
      let index = -1;
      if (name.search('::') > -1) {
          const varCount = name.split("::").length;
          if (varCount === 2) {
              name = name.split("::")[0];
              id = name.split("::")[1];
          } else if (varCount === 3) {
              name = name.split("::")[0];
              index = name.split("::")[1];
              id = name.split("::")[2];
          }
      } else {
          name = name;
      }
      let state = this.state;
      state[name.split('::').join('')] = value;
      this.setState(state, () => {
          if (this.props.onChange) {
              this.props.onChange({ type: 'textinput', name: name, value: value, index: index, id: id });
          }
      });
  }

  render() {
    
    return (
    <ScrollView data-layer="ebd53027-aa99-4ca9-b982-b14f92edf525" style={styles.meusservicos}>
        <View data-layer="6aa37b67-9ae0-48f6-8881-639f233aee11" style={styles.meusservicos_grupo7}>
            <Svg data-layer="4f28b113-79ac-4d29-ab44-9a2cc51d2c61" style={styles.meusservicos_grupo7_caminho6} preserveAspectRatio="none" viewBox="-0.75 -0.75 361.7500305175781 55.57647705078125" fill="rgba(253, 253, 253, 1)"><SvgPath d="M 0 0 L 360.0000305175781 0 L 360.0000305175781 53.82649993896484 L 0 53.82649993896484 L 0 0 Z"  /></Svg>
        </View>
        <View data-layer="87bbee21-4b05-45ce-9139-cd050598f651" style={styles.meusservicos_grupo10}>
            <Svg data-layer="a0467e7e-2128-4dc6-938a-75d9c12f3bcc" style={styles.meusservicos_grupo10_caminho3} preserveAspectRatio="none" viewBox="-0.75 -0.75 361.5 16.5" fill="rgba(190, 196, 198, 0.47058823529411764)"><SvgPath d="M 0 0 L 360 0 L 360 15 L 0 15 L 0 0 Z"  /></Svg>
        </View>
        <Text data-layer="e8f6909a-a0f9-4ff1-b63c-0c1f16046a00" style={styles.meusservicos_meusservicos245b3610}>Meus serviços</Text>
        <ReactImage data-layer="bf43665d-c203-4309-b948-9e57234286d8" source={require('./assets/seta.png')} style={styles.meusservicos_seta} />
        <View data-layer="6adcfe9d-672a-49fa-bf71-7401e34207ef" style={styles.meusservicos_grupo21}>
            <Svg data-layer="04d77fb4-b56c-4d0c-b5eb-43bef25cb062" style={styles.meusservicos_grupo21_caminho3712b4372} preserveAspectRatio="none" viewBox="-0.75 -0.75 361.5 16.5" fill="rgba(190, 196, 198, 0.47058823529411764)"><SvgPath d="M 0 0 L 360 0 L 360 15 L 0 15 L 0 0 Z"  /></Svg>
        </View>
        <View data-layer="754c3af8-aa6f-4d64-82e4-3c9253e584e7" style={styles.meusservicos_retangulo5}></View>
        <View data-layer="6867777f-df67-49da-88d8-0ae020066a96" style={styles.meusservicos_grupo42}>
            <ReactImage data-layer="f02fbae7-c1a4-4ff9-91e3-cc2971446895" source={require('./assets/elipse-1.png')} style={styles.meusservicos_grupo42_elipse1} />
        </View>
        <Text data-layer="cdbd7092-e5d4-4e9c-b7b1-d92ed1b66074" style={styles.meusservicos_bombeirohidraulico}>Bombeiro Hidráulico</Text>
        <Text data-layer="8042aa44-ff72-4111-9def-a95d1ebf9eaf" style={styles.meusservicos_substituicaodevasosanitario}>Substituição de vaso sanitário</Text>
        <Text data-layer="ccedf676-f5d3-4de6-b3c5-bca4622f6d21" style={styles.meusservicos_x24denovembrode2019}>24 de Novembro de 2019</Text>
        <Text data-layer="f0e41fa0-70eb-4925-a96e-62c14908af08" style={styles.meusservicos_r}>R$180,00</Text>
        <View data-layer="3830cce9-b663-47f5-b789-2fec59eff4dc" style={styles.meusservicos_retangulo14}></View>
        <Text data-layer="c151dc5e-41f4-4c94-9e43-9cf5e88089d7" style={styles.meusservicos_pedirajuda}>Pedir Ajuda</Text>
        <View data-layer="71f4dc39-7e05-4df8-80a4-d51356a1c6e3" style={styles.meusservicos_retangulo15}></View>
        <View data-layer="cee062a7-07dc-4be1-9efb-2d40588c6a91" style={styles.meusservicos_grupo43}>
            <ReactImage data-layer="178ae07c-2a04-410a-be82-261194566c1b" source={require('./assets/elipse-1-ec9d0f67.png')} style={styles.meusservicos_grupo43_elipse1f17b8c77} />
        </View>
        <Text data-layer="e1bb8cb1-0923-4829-b3ed-3739a462638e" style={styles.meusservicos_gasista}>Gasista</Text>
        <Text data-layer="a4f497fc-1210-4031-86cf-524675127a01" style={styles.meusservicos_instalacaodeaquecedor}>Instalação de aquecedor</Text>
        <Text data-layer="b7f4bf50-508a-4ebd-b79f-4ddbf0141d58" style={styles.meusservicos_x22denovembrode2019}>22 de Novembro de 2019</Text>
        <Text data-layer="5955ddea-96fd-4f67-8b1b-4346c77d437a" style={styles.meusservicos_r1}>R$150,00</Text>
        <ReactImage data-layer="bfcb953c-5df1-424a-bdcc-6ac513ecb693" source={require('./assets/app-papis.png')} style={styles.meusservicos_apppapis} />
        <View data-layer="de8ef6c0-0a3f-4283-941a-35adc23e3cf9" style={styles.meusservicos_retangulo16}></View>
        <Text data-layer="eecb7cb0-90dd-4456-98bd-584ccc5864d9" style={styles.meusservicos_pedirajuda1}>Pedir Ajuda</Text>
        <View data-layer="a126703f-72aa-4437-bde0-dd08593225af" style={styles.meusservicos_retangulo17}></View>
        <View data-layer="0b74df97-acac-4314-b5be-5e0b0403e3f9" style={styles.meusservicos_grupo44}>
            <ReactImage data-layer="fb33fb16-3926-4117-bffa-8e48e009cda7" source={require('./assets/elipse-1-87f8f407.png')} style={styles.meusservicos_grupo44_elipse19872356a} />
        </View>
        <Text data-layer="8f605c71-e13d-4576-aa65-732aff17505d" style={styles.meusservicos_gasista1}>Gasista</Text>
        <Text data-layer="4dd47ccc-df4f-4d57-886b-11669f6f1ede" style={styles.meusservicos_instalacaodeaquecedor1}>Instalação de aquecedor</Text>
        <Text data-layer="6b44875d-2fe4-4d08-9dd0-63929c80bf89" style={styles.meusservicos_x21denovembrode2019}>21 de Novembro de 2019</Text>
        <Text data-layer="e4018e63-ac17-4a7e-bb0c-a9a835a229d7" style={styles.meusservicos_r2}>R$140,00</Text>
        <View data-layer="683f67bc-603b-49ab-99f4-9e04914b1626" style={styles.meusservicos_retangulo18}></View>
        <Text data-layer="8c8c0e7a-3493-4c5f-8bce-e5bae5fa2ce0" style={styles.meusservicos_pedirajuda2}>Pedir Ajuda</Text>
        <ReactImage data-layer="8ba2c0d3-83db-404a-8966-6033831141a1" source={require('./assets/cancelado.png')} style={styles.meusservicos_cancelado} />
        <View data-layer="7447abe2-f223-4511-9d4a-f3a50d7e8622" style={styles.meusservicos_retangulo19}></View>
        <View data-layer="78a06588-1562-4249-bc8f-81fe665b7ede" style={styles.meusservicos_grupo45}>
            <ReactImage data-layer="e4d64e69-86eb-4c3e-9bee-7a57ef90eb08" source={require('./assets/elipse-1-c2d9ab28.png')} style={styles.meusservicos_grupo45_elipse150cac070} />
        </View>
        <Text data-layer="2cb8fafd-2765-40d3-a43b-8ed356657d32" style={styles.meusservicos_ladrilheiro}>Ladrilheiro</Text>
        <Text data-layer="94648dd6-adac-4b83-8f8e-0a922f19dfb9" style={styles.meusservicos_trocadepisoserevestimentos}>Troca de pisos e revestimentos</Text>
        <Text data-layer="e45c7bf1-593c-489d-b6c0-ec9c176cfb9f" style={styles.meusservicos_x10denovembrode2019}>10 de Novembro de 2019</Text>
        <Text data-layer="ff911c19-e3e2-437d-a612-5a9111ec8f6a" style={styles.meusservicos_r3}>R$1.050,00</Text>
        <ReactImage data-layer="11c12031-f9f7-480a-ab33-b33a9b0b4446" source={require('./assets/app-papis-880f735b.png')} style={styles.meusservicos_apppapis1} />
        <View data-layer="aa6654a6-a867-4079-a78b-e26838918e82" style={styles.meusservicos_retangulo20}></View>
        <Text data-layer="e5132b73-fbfa-41ca-a835-d98228cfc7fb" style={styles.meusservicos_pedirajuda3}>Pedir Ajuda</Text>
        <ReactImage data-layer="d03ac327-bcf1-496e-af77-82a22e25c7c9" source={require('./assets/progresso.png')} style={styles.meusservicos_progresso} />
        <View data-layer="4adb069f-5aa3-4382-ae00-51dc17b87e5b" style={styles.meusservicos_retangulo34}></View>
        <Text data-layer="e4e63d25-bd63-47d0-8305-3de28ff85139" style={styles.meusservicos_vermais}>Ver mais</Text>
        <View data-layer="e089bca2-5719-4446-8ce3-4bb6bf502b36" style={styles.meusservicos_retangulo72}></View>
        <Text data-layer="ca49a712-1bc4-4b08-b6e1-83d55bf2c48f" style={styles.meusservicos_vermais1}>Ver mais</Text>
        <View data-layer="74eaa792-5f53-45cc-83fe-22a67f8f597d" style={styles.meusservicos_retangulo73}></View>
        <Text data-layer="5c3132e7-2b97-4a17-a11e-0e81b4a8d6fc" style={styles.meusservicos_vermais2}>Ver mais</Text>
        <View data-layer="04a59fc8-5cd6-4d68-8134-809c6420f4de" style={styles.meusservicos_retangulo74}></View>
        <Text data-layer="0a36eb8d-1d2f-4d0a-9d7c-ad4b2a6b6703" style={styles.meusservicos_vermais3}>Ver mais</Text>
    </ScrollView>
    );
  }
}

Meusservicos.propTypes = {

}

Meusservicos.defaultProps = {

}


const styles = StyleSheet.create({
  "meusservicos": {
    "opacity": 1,
    "position": "relative",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 640,
    "left": 0,
    "top": 0
  },
  "meusservicos_grupo7": {
    "opacity": 0.4000000059604645,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 53.83,
    "left": 0,
    "top": 0
  },
  "meusservicos_grupo7_caminho6": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 363.5,
    "height": 57.33,
    "left": -1.5,
    "top": -1.5
  },
  "meusservicos_grupo10": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 15,
    "left": 0,
    "top": 626
  },
  "meusservicos_grupo10_caminho3": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 15,
    "left": 0,
    "top": 0
  },
  "meusservicos_meusservicos245b3610": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 20,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 132,
    "height": 27,
    "left": 105,
    "top": 14
  },
  "meusservicos_seta": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 25,
    "height": 16.29,
    "left": 12,
    "top": 19.26
  },
  "meusservicos_grupo21": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 15,
    "left": 0,
    "top": 53
  },
  "meusservicos_grupo21_caminho3712b4372": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 360,
    "height": 15,
    "left": 0,
    "top": 0
  },
  "meusservicos_retangulo5": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 362,
    "height": 87,
    "left": -1,
    "top": 67
  },
  "meusservicos_grupo42": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 47,
    "height": 47,
    "left": 18,
    "top": 80
  },
  "meusservicos_grupo42_elipse1": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 47,
    "height": 47,
    "left": 0,
    "top": 0
  },
  "meusservicos_bombeirohidraulico": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 146,
    "height": 20,
    "left": 93,
    "top": 75
  },
  "meusservicos_substituicaodevasosanitario": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 196,
    "height": 20,
    "left": 93,
    "top": 90
  },
  "meusservicos_x24denovembrode2019": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 147,
    "height": 17,
    "left": 93,
    "top": 107
  },
  "meusservicos_r": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 57,
    "height": 17,
    "left": 274,
    "top": 107
  },
  "meusservicos_retangulo14": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 216,
    "top": 127
  },
  "meusservicos_pedirajuda": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(36, 161, 77, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 55,
    "height": 14,
    "left": 228,
    "top": 129
  },
  "meusservicos_retangulo15": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 362,
    "height": 87,
    "left": -1,
    "top": 153
  },
  "meusservicos_grupo43": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 47,
    "height": 47,
    "left": 18,
    "top": 166
  },
  "meusservicos_grupo43_elipse1f17b8c77": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 47,
    "height": 47,
    "left": 0,
    "top": 0
  },
  "meusservicos_gasista": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 50,
    "height": 20,
    "left": 93,
    "top": 161
  },
  "meusservicos_instalacaodeaquecedor": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 161,
    "height": 20,
    "left": 93,
    "top": 176
  },
  "meusservicos_x22denovembrode2019": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 147,
    "height": 17,
    "left": 93,
    "top": 193
  },
  "meusservicos_r1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 57,
    "height": 17,
    "left": 274,
    "top": 193
  },
  "meusservicos_apppapis": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 31.5,
    "height": 26,
    "left": 306,
    "top": 163
  },
  "meusservicos_retangulo16": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 216,
    "top": 213
  },
  "meusservicos_pedirajuda1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(36, 161, 77, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 55,
    "height": 14,
    "left": 228,
    "top": 215
  },
  "meusservicos_retangulo17": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 362,
    "height": 87,
    "left": -1,
    "top": 239
  },
  "meusservicos_grupo44": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 47,
    "height": 47,
    "left": 18,
    "top": 252
  },
  "meusservicos_grupo44_elipse19872356a": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 47,
    "height": 47,
    "left": 0,
    "top": 0
  },
  "meusservicos_gasista1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 50,
    "height": 20,
    "left": 93,
    "top": 247
  },
  "meusservicos_instalacaodeaquecedor1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 161,
    "height": 20,
    "left": 93,
    "top": 262
  },
  "meusservicos_x21denovembrode2019": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 147,
    "height": 17,
    "left": 93,
    "top": 279
  },
  "meusservicos_r2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 57,
    "height": 17,
    "left": 274,
    "top": 279
  },
  "meusservicos_retangulo18": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 216,
    "top": 299
  },
  "meusservicos_pedirajuda2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(36, 161, 77, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 55,
    "height": 14,
    "left": 228,
    "top": 301
  },
  "meusservicos_cancelado": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 59,
    "height": 22,
    "left": 290,
    "top": 249
  },
  "meusservicos_retangulo19": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 362,
    "height": 87,
    "left": -1,
    "top": 324
  },
  "meusservicos_grupo45": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "transparent",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 47,
    "height": 47,
    "left": 18,
    "top": 338
  },
  "meusservicos_grupo45_elipse150cac070": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "width": 47,
    "height": 47,
    "left": 0,
    "top": 0
  },
  "meusservicos_ladrilheiro": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 76,
    "height": 20,
    "left": 93,
    "top": 333
  },
  "meusservicos_trocadepisoserevestimentos": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 15,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 203,
    "height": 20,
    "left": 93,
    "top": 348
  },
  "meusservicos_x10denovembrode2019": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 147,
    "height": 17,
    "left": 93,
    "top": 365
  },
  "meusservicos_r3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(0, 0, 0, 1)",
    "fontSize": 13,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 68,
    "height": 17,
    "left": 274,
    "top": 365
  },
  "meusservicos_apppapis1": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 31.5,
    "height": 26,
    "left": 306,
    "top": 335
  },
  "meusservicos_retangulo20": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 216,
    "top": 385
  },
  "meusservicos_pedirajuda3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(36, 161, 77, 1)",
    "fontSize": 10,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 55,
    "height": 14,
    "left": 228,
    "top": 387
  },
  "meusservicos_progresso": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 23,
    "borderTopRightRadius": 23,
    "borderBottomLeftRadius": 23,
    "borderBottomRightRadius": 23,
    "width": 56,
    "height": 14,
    "left": 286,
    "top": 81
  },
  "meusservicos_retangulo34": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(36, 161, 77, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 93,
    "top": 127
  },
  "meusservicos_vermais": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 37,
    "height": 14,
    "left": 113,
    "top": 128
  },
  "meusservicos_retangulo72": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(36, 161, 77, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 93,
    "top": 213
  },
  "meusservicos_vermais1": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 37,
    "height": 14,
    "left": 113,
    "top": 214
  },
  "meusservicos_retangulo73": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(36, 161, 77, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 93,
    "top": 299
  },
  "meusservicos_vermais2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 37,
    "height": 14,
    "left": 113,
    "top": 300
  },
  "meusservicos_retangulo74": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(36, 161, 77, 1)",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(36, 161, 77, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(36, 161, 77, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(36, 161, 77, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(36, 161, 77, 1)",
    "borderTopLeftRadius": 3,
    "borderTopRightRadius": 3,
    "borderBottomLeftRadius": 3,
    "borderBottomRightRadius": 3,
    "width": 78,
    "height": 18,
    "left": 93,
    "top": 385
  },
  "meusservicos_vermais3": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(255, 255, 255, 1)",
    "fontSize": 10,
    "fontWeight": "400",
    "fontStyle": "normal",
    "fontFamily": "segoe-ui",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 37,
    "height": 14,
    "left": 113,
    "top": 386
  }
});